#!/bin/bash

source ~/.local.secrets

# No salt is needed for decryption.
# Error messages are redirect to /dev/null.
openssl enc -d -base64 -aes-256-ecb -k "${GIT_OPENSSL_PASSWORD}" -in "$1" 2> /dev/null || cat "$1"

# Adopted from https://gist.github.com/sandeepraju/4934282f5f87c83ddd93
